#!/bin/sh
# Generate Lentils/Config/Generated.lean from .config
# Usage: ./scripts/gen-config.sh [.config] [Lentils/Config/Generated.lean]

CONFIG="${1:-.config}"
OUTPUT="${2:-Lentils/Config/Generated.lean}"

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" << 'HEADER'
-- AUTO-GENERATED by scripts/gen-config.sh. DO NOT EDIT.
namespace Lentils.Config.Generated

HEADER

TOTAL=0
ENABLED=0

while IFS= read -r line; do
  case "$line" in
    CONFIG_*=y)
      name="${line#CONFIG_}"
      name="${name%=y}"
      echo "def ${name}_enabled : Bool := true" >> "$OUTPUT"
      TOTAL=$((TOTAL + 1))
      ENABLED=$((ENABLED + 1))
      ;;
    "# CONFIG_"*"is not set")
      name="${line#\# CONFIG_}"
      name="${name% is not set}"
      name="${name% }"
      echo "def ${name}_enabled : Bool := false" >> "$OUTPUT"
      TOTAL=$((TOTAL + 1))
      ;;
  esac
done < "$CONFIG"

DISABLED=$((TOTAL - ENABLED))

cat >> "$OUTPUT" << 'FOOTER'

end Lentils.Config.Generated
FOOTER

echo "Generated $OUTPUT: $TOTAL applets (${ENABLED} enabled, ${DISABLED} disabled)"